[package]
name = "snotty"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
logos = "0.12.1"
cranelift = "0.93.0"
cranelift-jit = "0.93.0"
cranelift-module = "0.93.0"
once_cell = "1.16.0"
